version: "3"
services:
    api:
        container_name: api
        restart: always
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - "8080:8080"
        links:
            - mongodb
    frontend: 
        container_name: frontend
        restart: always
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - "3000:3000"
        links:
            - api
    mongodb:
        container_name: mongo
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27018:27017